id: ID1F79246
legacy_id: P008224
ocr_import_info:
  bdrc_scan_id: W19668
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T22:23:50'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:33:56.964106+00:00'
last_modified: 2022-08-30 23:34:16.608862
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19668
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19668
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཁྲིད་ཡིག ༼ཨ་འཛོམ་པར་མ།༽
  author: ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7417539640629521
  ocr_word_median_confidence_index: 0.8100000023841858
quality: null
bases:
  I1684:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1684
      total_pages: 300
      volume_number: 1
      volume_pages_bdrc_intro: 1
    order: 1
    base_file: I1684.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7417539640629521
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
