id: P008224
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:09:00.567245
source_metadata:
  id: bdr:W19668
  title: ཀློང་ཆེན་སྙིང་ཐིག་གི་སྔོན་འགྲོའི་ཁྲིད་ཡིག ༼ཨ་འཛོམ་པར་མ།༽
  author: ''
  volumes:
    bc962bccae1a4a09b5a009fae9d7c495:
      image_group_id: I1684
      title: ''
      volume_number: 1
      total_pages: 300
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
